### ISSUE TITLE
Replace or remove broken external links inside articles

### ISSUE THREAD

**Issue by query-string** [saberespoder/contenido#60]
As I remember – it should be a list of broken links saved somewhere and it would be great if we can eliminate all of them during this iteration. @stan2020, I'd be really appreciated if you could skim through the list and replace (or remove) these broken links from the articles.

Since all of the articles are on Contentful already you will need to ping @skatkov or @etavenn to obtain login and password for access. After that – Content section of `sepcontent` space is that you are looking for. All of the articles are searchable by title so hopefully, this task won't become very challenging (maybe just a bit boring). Please, let me know if you need any assistance with Contentful (though I'm sure it's quite intuitive). 

As I mentioned in comments to another issue #50 – once changes were applied and `Publish changes` button pressed it could take 2-3 minutes for changes to be reflected on the page.

**Comment by etavenn** [comment]
@query-string quick question:
Do we use the same log in info for all editors? I believe editors are using the tech@ account. That's the account log in info I was planing on giving @stan2020

**Comment by query-string** [comment]
@etavenn to be honest – I wouldn't recommend using _tech@_ account for editors mostly because, as always, it has superuser privileges (which means more power than just entries management). It is not that I'm expecting somebody will want to destroy content models or change sensitive settings purposely, but I always feel safer when critical abilities restricted :P

We actually have another `Tester Testerson` user with editor role which has been initially created for QA department, but I'm pretty sure – won't be used again (since the content is already migrated and it's nothin to QA on Contentful anymore). So I would either use this account or, if credentials were missing – destroyed `Tester Testerson` and created a new user with Editor role.

By the way – feel free to cancel these extra 1K records that we added to our Contentful plan month ago – we don't need them anymore either ;)

**Comment by stan2020** [comment]
@query-string sounds like that Tester Testerson account might be a good one for any contract/freelance editors/admins I want to have create or edit content on the platform.  

Erik, how much do new accounts cost?  I think 3 will be fine for now, but at some point you run into issues of tracking/attribution/accountability in terms of who's done what during a workflow.

**Comment by skatkov** [comment]
<img width="239" alt="screen shot 2017-05-04 at 21 26 26" src="https://cloud.githubusercontent.com/assets/544377/25718912/638617e8-3110-11e7-8b8f-afcc1b200e1f.png">

(c) https://www.contentful.com/pricing/

**Comment by stan2020** [comment]
Good to know.  Thx Stas.

**Comment by etavenn** [comment]
@stan2020 billing is already set up to add additional users should you want to add more down the line ;)

**Comment by etavenn** [comment]
@query-string @tzinchenko when could Tester account be available for use by the content team?

**Comment by stan2020** [comment]
Ok, Jholie and I fixed all the broken links in the URLs in [Tatiana's list](https://docs.google.com/spreadsheets/d/1et0CdKbYth6JH5nNfBC9IXGeIU8prkNUXp0cbuDNhx4/edit#gid=0).  Note that there was one article where I had formatting issues after fixing a link (in [this separate issue](https://github.com/saberespoder/inboundsms/issues/2390)) and [another](http://sepcontent.s3-website-us-east-1.amazonaws.com/articulos/educaci%C3%B3n/programa-de-ingles-de-saberespoder/) that was in the list but I couldn't find on Contentful.  The latter was for SEP's English service w/Voxy, which it sounds like might be defunct now anyway....  

LMK if there's anything else I can do on this task.  Thanks.

**Comment by query-string** [comment]
Thanks Stan, let's pass it to QA now ;)

**Comment by Victoria-Vachevskih** [comment]
@stan2020  There are still broken external links inside several articles. I've updated Tatiana's list, I've added [Sheet2](https://docs.google.com/spreadsheets/d/1et0CdKbYth6JH5nNfBC9IXGeIU8prkNUXp0cbuDNhx4/edit#gid=739959857)

**Comment by stan2020** [comment]
Thank you for catching those, @Victoria-Vachevskih.  I fixed the first one, but the link in the 2nd article was working for me.  In the 3rd one, I fixed the text and removed the bad link, but I don't see the changes taking effect in [the article](http://sepcontent.s3-website-us-east-1.amazonaws.com/articulos/inmigraci%C3%B3n/se-acerca-la-fecha-l-iacute-mite-para-beneficiarse-de-la-expansi-oacute-n-del-tps/).   I should mention that I did change the title [in Contentful](https://app.contentful.com/spaces/oa34n7smn7kt/entries/nxOThFIJ8c6waeCMgcWm), and now I can't find a live version with that new title (or my fixes).  Did changing the title mess it up somehow....?
